using Microsoft.AspNetCore.Html;
using SFA.DAS.TeachInFurtherEducation.Contentful.Model.Content;
using SFA.DAS.TeachInFurtherEducation.Contentful.Model.Content.Interfaces;
using SFA.DAS.TeachInFurtherEducation.Contentful.Model.Interim;
using System.Collections.Generic;

namespace SFA.DAS.TeachInFurtherEducation.Contentful.Content
{
    public class GeneratedContent : IContent
    {
        //  _    _                                _
        // | |  | |                              | |
        // | |__| | ___ _   _   _   _  ___  _   _| |
        // |  __  |/ _ \ | | | | | | |/ _ \| | | | |
        // | |  | |  __/ |_| | | |_| | (_) | |_| |_|
        // |_|  |_|\___|\__, |  \__, |\___/ \__,_(_)
        //               __/ |   __/ |
        //               |___/   |___/               
        //
        // this file is generated by the ContentCodeGenerator utility, so don't directly make changes here!!!
        //

        public IEnumerable<InterimPage> InterimPages
        {
            get
            {
                return new List<InterimPage>();
            }
        }

        public IEnumerable<MenuItem> MenuItems
        {
            get
            {
                // If _interimLandingPage is null, initialize it with a new InterimLandingPage instance
                return new List<MenuItem>()
                {

                    new MenuItem() 
                    { 
                        
                        MenuItemTitle = "Business Home - Menu Item",

                        MenuItemText = "Business Home",

                        MenuItemSource = "/",

                        MenuItemOrder = 1
                    
                    }

                };
            }
        }

        private Page? _interimLandingPage;

        public Page? Page
        {
            get
            {
                // If _interimLandingPage is null, initialize it with a new InterimLandingPage instance
                return _interimLandingPage ??= new Page("","", "", new List<TileSection>(), null, null);
            }
        }

        private IEnumerable<PageRenamed>? _pages;
        public IEnumerable<PageRenamed> Pagess => _pages ??= new PageRenamed[]
        {
            new PageRenamed("Environment",
                "environment",
                new HtmlString(@"<p class=""govuk-body"">master</p>")
            ),
            new PageRenamed("AnalyticsCookies",
                "analyticscookies",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Details about cookies</h1><p class=""govuk-body"">This service puts small files (known as &#39;cookies&#39;) onto your computer. These cookies are used to:</p><ul class=""govuk-list govuk-list--bullet""><li>help us understand how you use the website, so we can make improvements</li><li>remember what notifications you&#39;ve seen so you&#39;re not shown them more than once</li><li>temporarily store the selections you make</li></ul><p class=""govuk-body"">Find out more about&#160;<a href=""https://ico.org.uk/your-data-matters/online/cookies/"" title="""" class=""govuk-link"">how to manage cookies</a>.</p><h2 class=""govuk-heading-l"">Cookies that measure website usage</h2><p class=""govuk-body"">We use Google Analytics software (Universal Analytics) to collect anonymised information about how you use the service. We do this to help make sure the service is meeting the needs of its users and to help us make improvements.</p><p class=""govuk-body"">We do not allow Google to use or share the data about how you use this service.</p><p class=""govuk-body"">Google Analytics stores information about:</p><ul class=""govuk-list govuk-list--bullet""><li>how you got to the service</li><li>the pages you visit on this service and how long you spend on them</li><li>what you click on while you&#39;re visiting the service</li></ul><p class=""govuk-body"">We may also set our own cookies to understand how people move through the service.</p><p class=""govuk-body""></p>")
            ),
            new PageRenamed("MarketingCookies",
                "marketingcookies",
                new HtmlString(@"<h2 class=""govuk-heading-l"">Cookies that help with our communications and marketing</h2><p class=""govuk-body"">Some of our pages may contain content from other sites, like YouTube, which may set their own cookies. These sites are sometimes called &#39;third party&#39; services. This tells us how many people are seeing the content and whether it&#39;s useful.</p><p class=""govuk-body"">We also share information about your use of our pages with our social media and advertising partners (for example, Facebook) to help us improve the relevancy of advertising campaigns you receive from us.</p><p class=""govuk-body"">They may set cookies that you can turn off. Find out more about how to&#160;<a href=""https://ico.org.uk/your-data-matters/online/cookies/"" title="""" class=""govuk-link"">turn off these cookies</a>.</p><p class=""govuk-body"">In addition, if you share a link to one of our pages, the service you share it on (for example, Facebook) may set a cookie. We have no control over cookies set on other websites - you can turn them off, but not through us.</p><p class=""govuk-body""></p>")
            ),
            new PageRenamed("Accessibility statement",
                "accessibility-statement",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Accessibility statement</h1><p class=""govuk-body"">This accessibility statement applies to ""Find training and employment schemes for your business.""

This website is run by the Education and Skills Funding Agency. We want as many people as possible to be able to use this website. For example, that means you should be able to:</p><ul class=""govuk-list govuk-list--bullet""><li>
change colours, contrast levels and fonts
</li><li>zoom in up to 300% without the text spilling off the screen
</li><li>navigate most of the website using just a keyboard
</li><li>navigate most of the website using speech recognition software
</li><li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li></ul><p class=""govuk-body"">
We've also made the website text as simple as possible to understand.
<a href=""https://mcmw.abilitynet.org.uk/"" title="""" class=""govuk-link"">AbilityNet</a> has advice on making your device easier to use if you have a disability.

</p><h2 class=""govuk-heading-l"">
Feedback and contact information</h2><h2 class=""govuk-heading-l""></h2><p class=""govuk-body"">
If you need information on this website in a different format like accessible PDF, large print, easy read, audio recording or braille, email:
<a href=""ESFA.GOVUK-ENQUIRIES@education.gov.uk "" title="""" class=""govuk-link"">ESFA.GOVUK-ENQUIRIES@education.gov.uk </a>

We'll consider your request and get back to you in 5 working days.
</p><h2 class=""govuk-heading-l"">Reporting accessibility problems with this website</h2><p class=""govuk-body""></p><p class=""govuk-body"">
We're always looking to improve the accessibility of this website. 

If you find any problems not listed on this page or think we're not meeting accessibility requirements, contact: <a href=""ESFA.GOVUK-ENQUIRIES@education.gov.uk "" title="""" class=""govuk-link"">ESFA.GOVUK-ENQUIRIES@education.gov.uk</a>.
</p><h2 class=""govuk-heading-l"">Enforcement procedure
</h2><p class=""govuk-body"">The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the 'accessibility regulations'). 
</p><p class=""govuk-body"">If you're not happy with how we respond to your complaint, <a href=""https://www.equalityadvisoryservice.com/"" title="""" class=""govuk-link"">contact the Equality Advisory and Support Service (EASS)</a>.

</p><p class=""govuk-body""></p><h2 class=""govuk-heading-l"">Technical information about this website's accessibility</h2><p class=""govuk-body""></p><p class=""govuk-body"">Education and Skills Funding Agency is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

</p><h2 class=""govuk-heading-l"">Compliance status</h2><p class=""govuk-body"">

This website is fully compliant with the <a href=""https://www.w3.org/TR/WCAG21/"" title="""" class=""govuk-link"">Web Content Accessibility Guidelines version 2.1 AA standard</a>.

We know some of the content is above the reading age of 9. We will work to improve this.</p><p class=""govuk-body"">

</p><h2 class=""govuk-heading-l"">Preparation of this accessibility statement
</h2><p class=""govuk-body"">This statement was prepared on 22 December 2021. </p><p class=""govuk-body"">

This website was last tested on 13 December 2021. The test was carried out by the Education and Skills Funding Agency (ESFA) development team who built the website.</p><p class=""govuk-body""></p>")
            ),
            new PageRenamed("Home",
                "home",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Find training and employment schemes for your business</h1><p class=""govuk-body"">A range of government programmes, are available for employers who are considering hiring employees, offering work experience or upskilling existing staff, some of which offer financial incentives.</p>")
            ),
            new PageRenamed("Privacy Notice",
                "privacy-notice",
                new HtmlString(@"<h1 class=""govuk-heading-xl"">Privacy notice</h1><h2 class=""govuk-heading-l"">Who we are</h2><p class=""govuk-body"">This website is provided by the Education and Skills Funding Agency
(ESFA) which is a part of the Department for Education (DfE). For the
purpose of data protection legislation, the DfE is the data controller 
for the personal data processed as part of this website.</p><p class=""govuk-body"">We collect certain information or data about you when you use of this website if you 
agree to it. This includes your IP address, details of which version of web browser 
you used, information on you use the site, using cookies and page tagging 
techniques to help us improve the website.</p><p class=""govuk-body"">This helps us to improve the site by monitoring how you use it. We can't personally 
identify you using your data.</p><h2 class=""govuk-heading-l"">Keeping your data secure</h2><p class=""govuk-body"">We won't share your information with any other organisations for marketing, market 
research or commercial purposes, and we don't pass on your details to other 
websites.</p><h2 class=""govuk-heading-l"">Disclosing your information</h2><p class=""govuk-body"">We may pass on your information if we have a legal obligation to do so, or if we have
to enforce or apply our terms of use and other agreements. This includes exchanging
information with other government departments for legal reasons.</p><h2 class=""govuk-heading-l"">Links to other websites</h2><p class=""govuk-body"">This website contains links to other websites. This privacy policy only applies to this 
website. If you go to another website from this one, read the privacy policy on that 
website to find out what it does with your information.</p><h2 class=""govuk-heading-l"">Following a link to this website from another website</h2><p class=""govuk-body"">If you come to this website from another website, we may receive personal 
information about you from the other website. You should read the privacy policy of 
the website you came from to find out more about this.</p>")
            ),
        };

        private ContactPage? _contactPage;
        public ContactPage? ContactPage => _contactPage ??= new ContactPage() { ContactPageTitle = "Contact Page" };

        private BetaBanner? _betaBanner;
        public BetaBanner? BetaBanner => _betaBanner ??= new BetaBanner()
        {

            BetaBannerID = "employer-schemes-beta-banner",

            BetaBannerTitle = "Employer schemes beta banner"

        };

        public IEnumerable<FooterLink> FooterLinks
        {
            get
            {
                // If _interimLandingPage is null, initialize it with a new InterimLandingPage instance
                return new List<FooterLink>()
          {

              new FooterLink()
              {

               FooterLinkTitle = "Accessibility Statement",

               FooterLinkSource = "/page/accessibility-statement",

               FooterLinkText = "Accessibility",

               FooterLinkOrder = 1

              }

          };
            }
        }



        public IEnumerable<Page> Pages => throw new System.NotImplementedException();
    }
}
